### ISSUE TITLE
Test Fragments are no longer resolved in Feature when launching PDE JUnit Tests

### ISSUE THREAD

**Issue by Phillipus** [eclipse-pde/eclipse.pde#303]
- All my Junit 4 test bundles are in Fragments to test their host bundles
- I have one class in one plug-in (`com.archimatetool.tests`) that aggregates all of these tests into one `TestSuite` to run all of the test suites in those Fragments
- I've created a Feature project, `com.archimatetool.tests.feature`, that contains this one plug-in, `com.archimatetool.tests`, for convenience so I can select it in a launch configuration in Eclipse ("Features selected below") from PDE launch

This works fine on Eclipse 4.23.

However, since Eclipse 4.24 and later this doesn't work, as I get a `NoClassDefFoundError` when trying to run from PDE launch configuration. I now have to also add all of the Fragment test projects to the Feature project for it to run successfully. Whereas before these were resolved.

My question is - is this an intended change in Eclipse 4.24 or a bug?

**Comment by HannesWell** [comment]
> My question is - is this an intended change in Eclipse 4.24 or a bug?

Yes the launching of Eclipse apps has indeed been adjusted with 4.24 to not automatically add fragments to a launch just because their host participates. This behavior is not wanted in most cases and can cause hard to identify-problems. Furthermore there is no way to prevent a fragment from being included with the previous behavior.
In cases like yours you really have to add all fragments to that feature. 
Please see [Bug 578644](https://bugs.eclipse.org/bugs/show_bug.cgi?id=578644) for more elaboration on the topic.

**Comment by Phillipus** [comment]
@HannesWell Thank-you for your reply. I'm fine with this change, and indeed I have added all fragments to the feature. I just wanted to make sure this was intended and not a regression or bug.

So, I'll close this one, 👍 and thanks for your work on PDE!

**Comment by HannesWell** [comment]
> So, I'll close this one, 👍 and thanks for your work on PDE!

You're welcome. Thanks for providing feedback.
