### ISSUE TITLE
"PojoObservables cannot be resolved" error in org.eclipse.pde.spy.event

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-pde/eclipse.pde#339]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/323

org.eclipse.pde.spy.event has compilation error now.

@vogella : please make sure it is fixed before next build.
